Add generated crate metadata
oxidecomputer/progenitor pull request #233
Opened 2022-11-09 22:19 UTC by jayvdb

This adds a CLI arg for the crate registry to publish to, and a hardcoded `license` value which at least makes people think about licensing.
Ideally some other approach is found to make the crate metadata more easily customised without resorting to lots of CLI args.

2023-01-05 00:46 UTC, ahl requested changes

2023-01-05 00:46 UTC, ahl commented on progenitor/src/main.rs
> +    registry_name: String,
Let's make this optional.

2023-01-05 00:46 UTC, ahl commented on progenitor/src/main.rs
> +                license = \"UNLICENSED\"\n\
```suggestion
                # license = \"SPECIFY A LICENSE BEFORE PUBLISHING\"\n\
```

2023-01-17 22:51 UTC, jayvdb commented
@ahl , updated

2023-01-18 08:06 UTC, ahl approved these changes
looks good

2023-01-18 08:06 UTC, merged