Include Response bytes when payload didn't deserialize as expected
oxidecomputer/progenitor pull request #655
Opened 2023-12-13 22:30 UTC by epompeii

The current error handling for `progenatior-client` does not allow for reattempts at deserializing.
This is very useful when creating clients that will need a little more flexibility such as forwards compatibility.

This changeset breaks out the `InvalidResponsePayload` within `progenatior-client` into two separate errors:

- `InvalidResponseBytes`: When `reqwest` fails to actually get the bytes for the response.
- `InvalidResponsePayload`: When the payload didn't deserialize as expected, now also includes the bytes.

2023-12-18 19:36 UTC, ahl requested changes
This is great; thanks for doing this!

2023-12-18 19:36 UTC, ahl commented on progenitor-client/src/progenitor_client.rs
> +    InvalidResponseBytes(reqwest::Error),
How about:
```suggestion
    /// Encountered an error reading the body for an expected response.
    ResponseBodyError(reqwest::Error),
```

2023-12-18 19:36 UTC, ahl commented on progenitor-client/src/progenitor_client.rs
> +            Error::InvalidResponsePayload(_b, e) => {
we don't want to emit the bytes?

2023-12-18 19:36 UTC, ahl commented on progenitor-client/src/progenitor_client.rs
> +    InvalidUpgrade(reqwest::Error),
Let's move this up to be right after `CommunicationError` which is probably what this should have been initially.

```suggestion
    /// An error occurred when upgrading connection.
    UpgradeError(reqwest::Error),
```

2023-12-18 19:36 UTC, ahl commented on docs/progenitor-client.md
>      ErrorResponse(ResponseValue<E>),
let's add the upgrade error here as well

2023-12-18 19:36 UTC, ahl commented on progenitor-client/src/progenitor_client.rs
> +pub use bytes::Bytes;
does this need to be pub? `Error::InvalidResponsePayload`'s inner type isn't `pub`

2023-12-19 13:11 UTC, epompeii commented
Thanks for all the feedback, @ahl !
I have implemented all the suggested changes. Let me know if you see anything else 😃

2023-12-29 17:26 UTC, ahl approved these changes

2023-12-29 17:27 UTC, ahl commented
Thanks for this!

2023-12-29 17:27 UTC, merged