add mut request `pre_hook`
oxidecomputer/progenitor pull request #823
Opened 2024-06-06 10:16 UTC by drahnr

Currently `progenitor` supports `pre_hook`, `pre_hook_async` and `post_hook`, where the further get a `&reqwest::Request` passed.
The auth mechanism for an `OpenAPI` spec requires to _sign_ the encoded query and append two key value pairs to the request, as such the `pre-hook` appears to be the right place to adjust the `Request` accordingly.

Proposal:

Add `with_pre_hook_mut` in addition, allowing to modify the `Request` accordingly.

Considerations:

Since it's a per-request signature, modifying the `Client` itself is not sufficient.

Altneratives:

Change the API of the current `pre_hook` to take a `&mut` and use lint exception to avoid getting warnings on existing code.

2024-06-06 10:33 UTC, jclulow commented
FWIW, when I added `pre_hook_async` it was also for signing requests in a similar manner, and as such already gets a mutable reference to the request.

2024-06-06 12:12 UTC, drahnr commented
> FWIW, when I added `pre_hook_async` it was also for signing requests in a similar manner, and as such already gets a mutable reference to the request.

I'd be in favor to closing this PR and changing the sync hook API to take a `&mut Request`.

2024-06-12 22:48 UTC, ahl requested changes

2024-06-12 22:48 UTC, ahl commented on progenitor-impl/src/method.rs
>                  (#hook)(&#client.inner, &#request_ident);
let's just make this mut; it was probably a mistake to diverge the non-async and async variants. Let's not compound the mistake.

2024-06-12 22:51 UTC, closed without merging